name: Hello World

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: Hello World
      run: echo "Hello world"
  
  other:
    runs-on: ubuntu-latest

    steps:
    - name: list files
      run: ls -al